### ISSUE TITLE
Companion header for name-values pairs

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#20] opened 2017-09-25 20:23 UTC
Let's define the tags header that will contain name-value pairs that suppose to be propagated by tracing systems.

1. Call it `Correlation-Context`
2. Should be human readable
3. Make it appende-able (comma-separated) https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
4. If we need to specify the type of the value (int, bool) we can use the same approach as cookies - `name=value;type=int`

**Comment by yurishkuro** [comment] 2017-09-25 20:30
should there be some encoding if name/value are composed of unsafe characters for HTTP header value (or contain `= , ;`) ?

also, comma-separated is equivalent to repeating the header multiple times iirc, but does it put an implicit restriction on the length? I.e. if I have two long values, putting them into separate (identically named) headers will pass the proxies, but if one of them decides to reformat as comma-separated list, then it might exceed the max header length

**Comment by SergeyKanzhelev** [comment] 2017-09-25 20:36
making header append-able makes it easy to add another property without parsing existing header. For the proxy that appended headers - I think it may be just a limitation on size for now.

For encoding - maybe support urlencode?

**Comment by bogdandrutu** [comment] 2017-09-25 20:54
Couple of high level comments about this:
* What are the requirement/high level specs:
    * Do we want to have supported types for values?
    * Do we want to have limits on sizes?
    * Any restriction on the key/values characters?
* What is the encoding we use here?
    * base16/base64/other?

Let's define a bit what we try to achieve. It will be great if for example we decide on few types that we support, a set of size limits, etc. but I am fine if we cannot get an agreement.

**Comment by SergeyKanzhelev** [comment] 2017-09-25 23:25
Since we have general agreement - let's continue discussion in the PR https://github.com/TraceContext/tracecontext-spec/pull/21

**Comment by bogdandrutu** [comment] 2017-09-26 00:36
Closes as duplicate of this https://github.com/TraceContext/tracecontext-spec/issues/13?

**Closed as completed by bogdandrutu** 2017-09-26 00:36 UTC
