### ISSUE TITLE
Behaviour for invalid headers in forwarding mode not defined

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#220] opened 2018-12-18 16:10 UTC
The current spec defines that

_If the version prefix cannot be parsed (it's not 2 hex characters followed by
dash (`-`)), implementation should restart the trace_

If a system is in forwarding only mode. It , however, cannot start a trace. In this case the only possible decisions are to drop the headers or ignore that they are invalid.

**Comment by danielkhan** [comment] 2019-03-01 14:16
Is this a duplicate of https://github.com/w3c/trace-context/issues/251 @AloisReitbauer?

**Closed as completed** 2019-03-04 14:34 UTC
Labels: discuss-next-meeting
